const nodemailer = require('nodemailer');
const logger = require('./logger');

class EmailService {
    constructor() {
        this.transporter = null;
        this.enabled = false;

        if (process.env.SMTP_HOST && process.env.SMTP_USER && process.env.SMTP_PASS) {
            this.transporter = nodemailer.createTransport({
                host: process.env.SMTP_HOST,
                port: parseInt(process.env.SMTP_PORT) || 587,
                secure: parseInt(process.env.SMTP_PORT) === 465, // true only for port 465
                auth: {
                    user: process.env.SMTP_USER,
                    pass: process.env.SMTP_PASS
                },
                tls: {
                    rejectUnauthorized: false // Allow self-signed certs in dev
                }
            });
            this.enabled = true;
            logger.info('Email Service initialized successfully');
        } else {
            logger.warn('SMTP credentials missing. Email service disabled. Emails will be logged to console.');
        }
    }

    /**
     * Core send method
     * @param {Object} options - { email, subject, message, html }
     */
    async sendEmail(options) {
        if (!this.enabled) {
            logger.info(`[DEV EMAIL] To: ${options.email} | Subject: ${options.subject}\n${options.message}`);
            return { messageId: 'dev-mock', devMode: true };
        }

        const fromName = process.env.FROM_NAME || 'TechDV';
        const fromEmail = process.env.FROM_EMAIL || process.env.SMTP_USER;

        const message = {
            from: `"${fromName}" <${fromEmail}>`,
            to: options.email,
            subject: options.subject,
            text: options.message,
            html: options.html
        };

        try {
            const info = await this.transporter.sendMail(message);
            logger.info(`Email sent: ${info.messageId}`);
            return info;
        } catch (error) {
            logger.error(`Nodemailer Error: ${error.message}`);
            throw new Error('Email could not be sent');
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // EMAIL OTP VERIFICATION
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Send email verification OTP during registration.
     * @param {string} email - Recipient email
     * @param {string} name - User's first name
     * @param {string} otp - Plain 6-digit OTP (generated by controller)
     */
    async sendEmailOTPVerification(email, name, otp) {
        const subject = 'Verify Your Email — TechDV OTP Code';
        const message = `Hello ${name},\n\nYour TechDV email verification OTP is: ${otp}\n\nThis OTP is valid for 10 minutes.\n\nIf you did not create this account, please ignore this email.\n\nRegards,\nTechDV Team`;

        const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Email Verification</title>
</head>
<body style="margin:0;padding:0;background-color:#0a0a0a;font-family:'Inter',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0a0a0a;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="560" cellpadding="0" cellspacing="0" style="background:linear-gradient(135deg,#111111 0%,#1a1a1a 100%);border-radius:24px;border:1px solid #2a2a2a;overflow:hidden;">

          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#6366f1 0%,#8b5cf6 100%);padding:36px 40px;text-align:center;">
              <h1 style="margin:0;color:#ffffff;font-size:28px;font-weight:900;letter-spacing:-0.5px;text-transform:uppercase;">TechDV</h1>
              <p style="margin:8px 0 0;color:rgba(255,255,255,0.75);font-size:13px;font-weight:500;letter-spacing:2px;text-transform:uppercase;">Email Verification</p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:48px 40px;">
              <p style="margin:0 0 8px;color:#a0a0a0;font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:1px;">Hello,</p>
              <h2 style="margin:0 0 24px;color:#ffffff;font-size:24px;font-weight:800;">${name}</h2>

              <p style="margin:0 0 32px;color:#888888;font-size:15px;line-height:1.6;">
                Thank you for registering at <strong style="color:#a78bfa;">TechDV</strong>. 
                Use the verification code below to confirm your email address and activate your account.
              </p>

              <!-- OTP Box -->
              <div style="background:#0d0d0d;border:1px solid #2a2a2a;border-radius:16px;padding:32px;text-align:center;margin-bottom:32px;">
                <p style="margin:0 0 16px;color:#6b7280;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:3px;">Your Verification Code</p>
                <div style="display:inline-block;">
                  <span style="font-size:48px;font-weight:900;color:#a78bfa;letter-spacing:12px;font-family:'Courier New',monospace;">${otp}</span>
                </div>
                <p style="margin:20px 0 0;color:#4b5563;font-size:13px;">
                  ⏱ This code expires in <strong style="color:#f59e0b;">10 minutes</strong>
                </p>
              </div>

              <div style="background:#111827;border-left:3px solid #6366f1;border-radius:4px;padding:16px 20px;margin-bottom:32px;">
                <p style="margin:0;color:#9ca3af;font-size:13px;line-height:1.6;">
                  🔒 <strong style="color:#e5e7eb;">Security Notice:</strong> 
                  TechDV will never ask you for this code via phone or chat. 
                  Do not share this OTP with anyone.
                </p>
              </div>

              <p style="margin:0;color:#6b7280;font-size:13px;line-height:1.6;">
                If you did not create a TechDV account, you can safely ignore this email. 
                No account will be activated without verification.
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#0d0d0d;padding:24px 40px;border-top:1px solid #2a2a2a;text-align:center;">
              <p style="margin:0;color:#4b5563;font-size:12px;">
                © ${new Date().getFullYear()} TechDV. All rights reserved.
              </p>
              <p style="margin:8px 0 0;color:#374151;font-size:11px;">
                This is an automated message. Please do not reply to this email.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

        return this.sendEmail({ email, subject, message, html });
    }

    // ─────────────────────────────────────────────────────────────────────────
    // WELCOME EMAIL
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Send welcome email after successful verification.
     * @param {string} email
     * @param {string} name
     */
    async sendWelcomeEmail(email, name) {
        const subject = 'Welcome to TechDV — Account Verified ✅';
        const message = `Hi ${name},\n\nYour email has been verified and your TechDV account is now active. Start exploring our courses today!\n\nRegards,\nTechDV Team`;

        const html = `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background-color:#0a0a0a;font-family:'Inter',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0a0a0a;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="560" cellpadding="0" cellspacing="0" style="background:#111111;border-radius:24px;border:1px solid #2a2a2a;overflow:hidden;">
          <tr>
            <td style="background:linear-gradient(135deg,#059669 0%,#10b981 100%);padding:36px 40px;text-align:center;">
              <h1 style="margin:0;color:#ffffff;font-size:28px;font-weight:900;letter-spacing:-0.5px;text-transform:uppercase;">TechDV</h1>
              <p style="margin:8px 0 0;color:rgba(255,255,255,0.8);font-size:13px;font-weight:500;letter-spacing:2px;text-transform:uppercase;">Account Verified ✓</p>
            </td>
          </tr>
          <tr>
            <td style="padding:48px 40px;">
              <h2 style="margin:0 0 16px;color:#ffffff;font-size:24px;font-weight:800;">Welcome aboard, ${name}! 🚀</h2>
              <p style="color:#888888;font-size:15px;line-height:1.6;margin:0 0 32px;">
                Your account is now fully verified and active. You can now log in and start your learning journey.
              </p>
              <a href="${process.env.FRONTEND_URL?.split(',')[0] || 'http://localhost:5173'}/login" 
                style="display:inline-block;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#ffffff;padding:14px 32px;border-radius:12px;text-decoration:none;font-weight:700;font-size:14px;letter-spacing:1px;text-transform:uppercase;">
                Start Learning →
              </a>
            </td>
          </tr>
          <tr>
            <td style="background:#0d0d0d;padding:24px 40px;border-top:1px solid #2a2a2a;text-align:center;">
              <p style="margin:0;color:#4b5563;font-size:12px;">© ${new Date().getFullYear()} TechDV. All rights reserved.</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

        return this.sendEmail({ email, subject, message, html });
    }

    // ─────────────────────────────────────────────────────────────────────────
    // PASSWORD RESET
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Send password reset OTP email.
     * @param {string} email
     * @param {string} otp
     */
    async sendPasswordResetEmail(email, otp) {
        const subject = 'Password Reset OTP — TechDV';
        const message = `You requested a password reset. Your OTP is: ${otp}\nThis code is valid for 10 minutes. If you did not request this, please ignore.`;

        const html = `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background-color:#0a0a0a;font-family:'Inter',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#0a0a0a;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="560" cellpadding="0" cellspacing="0" style="background:#111111;border-radius:24px;border:1px solid #2a2a2a;overflow:hidden;">
          <tr>
            <td style="background:linear-gradient(135deg,#dc2626 0%,#f97316 100%);padding:36px 40px;text-align:center;">
              <h1 style="margin:0;color:#ffffff;font-size:28px;font-weight:900;letter-spacing:-0.5px;text-transform:uppercase;">TechDV</h1>
              <p style="margin:8px 0 0;color:rgba(255,255,255,0.8);font-size:13px;font-weight:500;letter-spacing:2px;text-transform:uppercase;">Password Reset</p>
            </td>
          </tr>
          <tr>
            <td style="padding:48px 40px;">
              <p style="color:#888888;font-size:15px;line-height:1.6;margin:0 0 32px;">
                We received a password reset request for your account. Use the code below:
              </p>
              <div style="background:#0d0d0d;border:1px solid #2a2a2a;border-radius:16px;padding:32px;text-align:center;margin-bottom:32px;">
                <p style="margin:0 0 16px;color:#6b7280;font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:3px;">Reset Code</p>
                <span style="font-size:48px;font-weight:900;color:#f97316;letter-spacing:12px;font-family:'Courier New',monospace;">${otp}</span>
                <p style="margin:20px 0 0;color:#4b5563;font-size:13px;">⏱ Expires in <strong style="color:#f59e0b;">10 minutes</strong></p>
              </div>
              <p style="margin:0;color:#6b7280;font-size:13px;">
                If you did not request this, ignore this email. Your password will remain unchanged.
              </p>
            </td>
          </tr>
          <tr>
            <td style="background:#0d0d0d;padding:24px 40px;border-top:1px solid #2a2a2a;text-align:center;">
              <p style="margin:0;color:#4b5563;font-size:12px;">© ${new Date().getFullYear()} TechDV. All rights reserved.</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

        return this.sendEmail({ email, subject, message, html });
    }
}

module.exports = new EmailService();
